services:
  devcontainer:
    container_name: fixtures_library_devcontainer
    build: .
    volumes:
      - ./:/workspace:cached
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED}
      - PHP_VERSION=${PHP_VERSION}
