name: Quality analysis

on: [ push ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Psalm
        run: vendor/bin/psalm

  ecs:
    name: Easy coding standard
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: ECS
        run: ./vendor/bin/ecs check

  composer_normalize:
    name: composer.json normalizer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: composer normalize
        run: composer normalize --dry-run

  composer_validate:
    name: composer.json validation
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate

  phpunit:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Run tests
        run: vendor/bin/phpunit

  infection:
    name: Run mutation tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Download Infection
        run: wget https://github.com/infection/infection/releases/download/0.25.0/infection.phar && chmod +x infection.phar

      - name: Verify Infection
        run: wget https://github.com/infection/infection/releases/download/0.25.0/infection.phar.asc && gpg --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0 && gpg --with-fingerprint --verify infection.phar.asc infection.phar

      - name: Run mutation tests
        run: ./infection.phar --min-msi=100 --min-covered-msi=100
