name: QA

on: [ push ]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Psalm
        run: vendor/bin/psalm

  ecs:
    name: Easy coding standard
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: ECS
        run: ./vendor/bin/ecs check

  ecs_markdown:
    name: Easy coding standard for Markdown
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: ECS
        run: ./vendor/bin/ecs check-markdown README.md docs/advanced.md

  composer_normalize:
    name: composer.json normalizer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: composer normalize
        run: composer normalize --dry-run

  composer_validate:
    name: composer.json validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate

  phpunit:
    name: Unit & integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: PHPUnit
        run: vendor/bin/phpunit

  infection:
    name: Mutation tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Download Infection
        run: wget https://github.com/infection/infection/releases/download/0.25.0/infection.phar

      - name: Add execution permissions
        run: chmod +x infection.phar

      - name: Infection
        run: ./infection.phar --min-msi=100 --min-covered-msi=100

  composer_require_checker:
    name: Composer Require Checker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Cache tools installed with PHIVE
        uses: actions/cache@v2.1.2
        with:
          path: ${{ runner.temp }}/.phive
          key: php-${{ matrix.php }}-phive-${{ hashFiles('.phive/phars.xml') }}
          restore-keys: php-${{ matrix.php }}-phive-

      - name: Install PHIVE
        uses: szepeviktor/phive@v1
        with:
          home: ${{ runner.temp }}/.phive
          binPath: ${{ github.workspace }}/tools/phive

      - name: Install PHP tools with PHIVE
        uses: szepeviktor/phive-install@v1
        with:
          home: ${{ runner.temp }}/.phive
          binPath: ${{ github.workspace }}/tools/phive
          trustGpgKeys: C5095986493B4AA0,033E5F8D801A2F8D

      - name: Composer Require Checker
        run: php tools/composer-require-checker

  yamllint:
    name: Yamll
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
          file_or_dir: .
          strict: true
