name: Static Code Analysis

on: [ push ]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        composer-preference:
          - lowest
          - highest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.composer-preference == 'highest'
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Install dependencies
        if: matrix.composer-preference == 'lowest'
        run: composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        composer-preference:
          - lowest
          - highest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.composer-preference == 'highest'
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Install dependencies
        if: matrix.composer-preference == 'lowest'
        run: composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - name: Psalm
        run: vendor/bin/psalm

  composer-require-checker:
    name: Composer Require Checker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        composer-preference:
          - lowest
          - highest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.composer-preference == 'highest'
        run: composer update --no-interaction --no-progress --no-ansi

      - name: Install dependencies
        if: matrix.composer-preference == 'lowest'
        run: composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - name: Cache tools installed with PHIVE
        uses: actions/cache@v2.1.2
        with:
          path: ${{ runner.temp }}/.phive
          key: php-${{ matrix.php }}-phive-${{ hashFiles('.phive/phars.xml') }}
          restore-keys: php-${{ matrix.php }}-phive-

      - name: Install PHIVE
        uses: szepeviktor/phive@v1
        with:
          home: ${{ runner.temp }}/.phive
          binPath: ${{ github.workspace }}/tools/phive

      - name: Install PHP tools with PHIVE
        uses: szepeviktor/phive-install@v1
        with:
          home: ${{ runner.temp }}/.phive
          binPath: ${{ github.workspace }}/tools/phive
          trustGpgKeys: C5095986493B4AA0,033E5F8D801A2F8D

      - name: Composer Require Checker
        run: php tools/composer-require-checker
